language: objective-c

notifications:
  email:
    on_success: never
    on_failure: change

git:
  depth: 10

branches:
  only:
    - master

script:
  # See https://github.com/atom/ci
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - apm publish patch
